# .github/workflows/run_and_push.yml
name: Run Earthquake Bot

on:
  workflow_dispatch:

jobs:
  run-and-push:
    runs-on: ubuntu-latest
    env:
      CHAT_ID: ${{ secrets.CHAT_ID }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # full history for force push

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python main.py

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit DB changes
        run: |
          git add db/
          git commit -m "Update database" || echo "No changes to commit"

      - name: Force push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin HEAD:main --force
